import React, { createContext, useContext, useState, useEffect } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

type Language = "en" | "uz" | "ru";

type Translations = {
  [key: string]: string;
};

const translations: Record<Language, Translations> = {
  en: {
    // Dashboard
    hello: "Hello",
    friend: "Friend",
    readyToCrush: "Ready to crush the SAT?",
    createPlan: "Create Plan",
    startTimer: "Start Timer",
    target: "Target",
    editGoal: "Edit Goal",
    completeProfile: "Complete Your Profile",
    completeProfileSub:
      "Set your name and exam date to personalize your dashboard.",
    todaysPlans: "TODAY'S PLANS",
    fullCheckIn: "Full Check-in",
    noPlansToday: "No plans set for today",
    successQuote: "Success doesn't just happen. It's planned.",
    createAPlan: "Create a Plan",
    active: "ACTIVE",
    done: "DONE",
    enterStudyRoom: "Enter Study Room",
    buildStreak: "Build Your Streak",
    streakSub:
      "Consistent study is the key to a high score. Check in daily to build your momentum.",
    goToCheckIn: "Go to Check-in",
    studyRoom: "Study Room",
    studyRoomSub:
      "Execute your scheduled objectives with integrated piece-by-piece management.",
    goToStudyRoom: "Go to Study Room",
    quickLinks: "QUICK LINKS",
    studyPlanner: "Study Planner",
    dailyCheckIn: "Daily Check-in",
    studyHistory: "Study History",
    classicTimer: "Classic Timer",
    studyTip: "Study Tip",
    tipQuote:
      '"The secret of getting ahead is getting started." — Stay consistent with your daily plans to reach your target score.',
    loadingDashboard: "Loading Dashboard...",
    feedback: "Feedback",
    haveSuggestions: "Have suggestions?",
    planClosed: "Plan Closed",
    sessionUnavailableMsg: "This session is already completed or expired.",
    standBy: "Stand By",
    planScheduledFor:
      "This plan is scheduled for {time}. Access will open then.",

    // Profile / Settings
    settings: "Settings",
    preferencesAccount: "Preferences & Account",
    themeEngine: "Theme Engine",
    classic: "Classic",
    midnight: "Midnight",
    ocean: "Ocean",
    quickAccess: "Quick Access",
    editProfile: "Edit Profile",
    studyArchive: "Study Archive",
    general: "General",
    shareFeedback: "Share Feedback",
    aboutApp: "About Application",
    privacyPolicy: "Privacy Policy",
    signOut: "Sign Out",
    language: "Language",
    selectLanguage: "Select Language",

    // Common
    error: "Error",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",

    // Plan Screen
    editPlan: "Edit Plan",
    plan: "Plan",
    refineMission: "Refine your mission.",
    designPath: "Design your path to mastery.",
    selectScheduleDate: "Select Schedule Date",
    focusArea: "Focus Area",
    startTime: "START TIME",
    endTime: "END TIME",
    executionTasks: "Execution Tasks",
    divideSession: "Divide your session into specific tasks...",
    saving: "Saving...",
    updateMission: "Update Mission",
    commitMission: "Commit Mission",
    instructions: "Instructions",
    planInstructions:
      "Choose the section you want to study and set a clear timeframe. Be specific about your tasks to maintain focus. Once saved, these plans will appear in your dashboard and check-in timeline.",
    math: "MATH",
    reading: "READING",
    writing: "WRITING",
    hour: "HOUR",
    min: "MIN",
    pleaseEnterTasks: "Please enter some tasks",
    minutesExceed59: "Minutes cannot exceed 59.",
    endTimeFuture: "The mission end time must be in the future.",
    minDuration: "Minimum plan duration is 5 minutes.",
    failedLoadPlan: "Failed to load plan for editing.",
    missionUpdated: "Mission updated successfully!",
    missionCommitted: "Mission committed successfully!",

    // Check-in Screen
    checkIn: "Check-in",
    timelineSub: "Click a day to view or mark plans",
    fullTimeline: "FULL TIMELINE",
    today: "TODAY",
    noCheckIns: "No plans for this day.",
    scheduleNow: "Schedule Now →",
    howItWorks: "How it works",
    checkInInfo1:
      'Sessions become available for check-in after their scheduled start time. Mark your plans as "Completed" if you finished your tasks, or "Missed" if you couldn\'t make it.',
    checkInInfo2:
      "Consistent check-ins help you track your progress and maintain study accountability over time.",
    incomplete: "Incomplete",
    finished: "Finished",
    scheduleNewMission: "Schedule New Mission",
    missionDeleted: "Mission deleted successfully",
    failedDelete: "Failed to delete mission",
    sureDelete:
      "Are you sure you want to delete this mission? This cannot be undone.",
    locked: "Locked",
    onlyCheckInAfterStart: "You can only check in after the plan starts.",
    deletePlan: "Delete Plan",

    // Study Room
    studySession: "Study Session",
    activeMission: "Active Mission",
    objectiveProgress: "OBJECTIVE PROGRESS",
    timerRemaining: "REMAINING",
    finishMission: "Finish Mission",
    syncingRoom: "Syncing Room...",
    dailyRoadmap: "Execute your daily roadmap",
    allMissionsComplete: "All missions for today are complete or unlisted.",
    planNewMission: "Plan New Mission",
    missionBriefing: "Mission Briefing",
    totalTime: "TOTAL TIME",
    window: "WINDOW",
    configureStrategy: "Configure Strategy",
    piecesSessions: "PIECES (SESSIONS)",
    breakPerPiece: "BREAK PER PIECE (m)",
    strategyInfo: "Strategy: {sessions} pieces of {focus}m focus each.",
    missionSuccess: "Mission Success",
    missionSuccessSub:
      "You've completed your intensive study of {section}. Ready to log your progress?",
    logAsCompleted: "LOG AS COMPLETED",
    archiving: "ARCHIVING...",
    keepWorking: "KEEP WORKING",
    quitSession: "QUIT SESSION",
    overallCompletion: "OVERALL COMPLETION",
    missionObjective: "MISSION OBJECTIVE",
    partXofY: "Part {current} of {total}",
    quitSessionTitle: "Quit Session?",
    quitSessionMsg: "Do you want to save your progress or discard it?",
    discard: "Discard",
    saveProgress: "Save",
    resetPieceMsg:
      "Restart this piece? Current progress for this session will be lost.",
    expired: "Expired",
    startsAt: "Starts {time}",
    continue: "Continue",
    missionUnavailable: "Mission Unavailable",
    alreadyCompleted: "This mission is already completed.",
    alreadyExpired: "This mission has expired.",
    failedLoadPlans:
      "Failed to load study plans. Please check your connection.",
    selectDate: "Select Date",
    noRecordsDate: "No records for this date",
    missed: "MISSED",
    untracked: "UNTRACKED",
    deleteRecord: "Delete Record",
    sureDeleteRecord:
      "Are you sure you want to delete this study record? This cannot be undone.",
    recordDeleted: "Record deleted successfully",
    failedDeleteRecord: "Failed to delete record",
    failedLoadHistory: "Failed to load history.",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",

    // Edit Profile
    personalInfo: "Personal Information",
    name: "Name",
    yourName: "Your name",
    educationLevel: "Education Level",
    satScores: "SAT Scores",
    targetScore: "Target Score",
    readingWriting: "Reading & Writing",
    totalTarget: "Total Target",
    previousScoreOptional: "Previous Score (Optional)",
    havePreviousScore: "I have a previous SAT score",
    previousTotal: "Previous Total",
    saveChanges: "Save Changes",
    profileUpdated: "Profile updated successfully!",
    failedUpdateProfile:
      "Failed to update profile. Please check your connection.",
    failedLoadProfile: "Failed to load profile. Please check your connection.",
    undergraduate: "Undergraduate",
    graduate: "Graduate",
    other: "Other",
    "5th": "5th Grade",
    "6th": "6th Grade",
    "7th": "7th Grade",
    "8th": "8th Grade",
    "9th": "9th Grade",
    "10th": "10th Grade",
    "11th": "11th Grade",
    "12th": "12th Grade",
    march: "March",
    may: "May",
    june: "June",
    august: "August",
    october: "October",
    november: "November",
    december: "December",
    aboutSATTracker: "About SAT Tracker",
    premiumStudyCompanion: "Premium Study Companion",
    planTrackSucceed: "Plan. Track. Succeed.",
    aboutHeroDesc:
      "A comprehensive tool for modern SAT preparation. Organize your daily sessions, maintain focus, and track your progress consistently.",
    everythingYouNeed: "Everything You Need",
    smartToolsDesc:
      "Smart tools designed to increase your study habits and maximize efficiency.",
    readyOptimizeSAT: "Ready to Optimize Your SAT Study?",
    aboutCTADesc:
      "Stay consistent with your daily plans to reach your target score. Consistent effort is the bridge between goals and accomplishment.",
    studyPlanningDesc:
      "Create structured daily plans for Math, Reading, and Writing sections. Set specific time blocks for each task.",
    focusTimerLongDesc:
      "Increase focus with work-rest intervals. Integrated directly with your study plans for seamless session tracking.",
    dailyCheckInsLongDesc:
      "Maintain accountability by marking your sessions as completed. Build a daily streak of productivity.",
    progressTrackerDesc:
      "View your performance history. See exactly which sessions you completed and identify areas for improvement.",
    privacyHeroSub:
      "Your privacy matters to us. Here's how we handle your data.",
    lastUpdated: "Last Updated: January 2026",
    questions: "Questions?",
    privacyQuestionsSub:
      "If you have any questions about this privacy policy or how we handle your data, please reach out:",
    dataCollection: "Data Collection",
    dataCollectionContent:
      "SAT Tracker collects only the essential information needed to provide our service: your email address for authentication, study plans you create, and check-in records. We do not collect personal identifying information beyond what you explicitly provide.",
    dataStorage: "Data Storage",
    dataStorageContent:
      "Your data is securely stored using Supabase's cloud infrastructure with industry-standard encryption. All data transmissions are encrypted using TLS/SSL protocols.",
    dataUsage: "Data Usage",
    dataUsageContent:
      "We use your data solely to provide the SAT Tracker service. Your study plans and progress data are never shared with third parties, sold, or used for advertising purposes.",
    yourRights: "Your Rights",
    yourRightsContent:
      "You have the right to access, modify, or delete your data at any time. To request data deletion, please contact us via Telegram at @satrackerbot.",

    // Focus / Classic Timer
    classicPomodoro: "Focus Timer",
    focusSub: "Pure Concentration Zone",
    focusProgress: "FOCUS PROGRESS",
    ready: "READY",
    focusing: "FOCUSING",
    breaking: "BREAKING",
    adjustSessions: "ADJUST SESSIONS",
    focusDuration: "Focus Duration (m)",
    breakDuration: "Break Duration (m)",
    configTip: "You can type numbers or use +/- while paused.",
    resetTimer: "Reset Timer",
    confirmReset:
      "Are you sure you want to reset the current session? Progress will be lost.",
    session: "Session",
    break: "Break",
    start: "Start",
    pause: "Pause",
    reset: "Reset",
    success: "Success",
    notAuthenticated: "Not authenticated",
    noInternet: "No internet connection.",
    failedSavePlan: "Failed to save plan.",
    failedSaveStatus: "Failed to save status.",
    examDate: "Exam Date",
    allRightsReserved: "All Rights Reserved",
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to continue your SAT prep journey",
    emailAddress: "Email address",
    signIn: "Sign In",
    signingIn: "Signing In...",
    forgotPassword: "Forgot your password?",
    or: "OR",
    createNewAccount: "Create New Account",
    backToSignIn: "Back to Sign In",
    checkYourEmail: "Check Your Email",
    weSentResetLink: "We've sent a password reset link to {email}",
    resendEmail: "Resend Email",
    resending: "Resending...",
    needHelp: "Need help?",
    enterEmailReset: "Enter your email and we'll send you a reset link",
    sendResetLink: "Send Reset Link",
    sending: "Sending...",
    createAccount: "Create Account",
    tellUsAboutYou: "Tell Us About You",
    satGoals: "Your SAT Goals",
    setUpCredentials: "Set up your credentials",
    personalizeExperience: "We'll personalize your experience",
    trackProgress: "Help us track your progress",
    preferredName: "Preferred Name",
    namePlaceholder: "What should we call you?",
    confirmPassword: "Confirm new password",
    hints: "At least 6 characters, with letters and numbers",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    checking: "Checking...",
    completeSignup: "Complete Signup",
    creatingAccount: "Creating Account...",
    skip: "Skip",
    notifications: "Notifications",
    newUpdates: "NEW UPDATES",
    pastNotifications: "PAST NOTIFICATIONS",
    noNotificationsYet: "No notifications yet",
    showMore: "Show More",
    showLess: "Show Less",
    goToPlanner: "Go to Planner",
    checkInNow: "Check-in Now",
    markAllRead: "Mark all as read",
    planUnavailable: "Plan Unavailable",
    invalidCredentials:
      "Wrong credentials for log-in. Please check your email and password.",
    emailNotConfirmed: "Please verify your email address before logging in.",
    userNotFound: "This email does not exist for log in.",
    loginFailed: "Login failed. Please try again.",
    failedSendReset: "Failed to send reset email.",
    enterEmail: "Please enter your email address.",
    enterPassword: "Please enter your password.",
    createPassword: "Please create a new password.",
    passwordRequirements:
      "The password should be at least 6 characters and contain both letters and numbers.",
    passwordsDoNotMatch: "Confirm password does not match. Please try again.",
    completeRequiredFields:
      "Please complete all required fields to personalize your experience.",
    accountCreatedSuccess: "Account created successfully!",
    checkEmailVerify: "Please check your email to verify your account.",
    unexpectedError: "An unexpected error occurred.",
    userAlreadyExists: "The user already exists. Enter a different email.",
    invalidEmail: "Enter a correct email address.",
    january: "January",
    february: "February",
    april: "April",
    july: "July",
    september: "September",
    daysShort: "D",
    hoursShort: "H",
    minutesShort: "M",
    secondsShort: "S",
    at: "at",
    failedFetchData: "Failed to fetch data. Server error.",
    noInternetCheck:
      "No internet connection. Please check your network and try again.",

    // Premium Page
    getPremium: "Get Premium",
    unlockAllFeatures: "Unlock all features and maximize your SAT prep",
    whatYouGet: "What You Get",
    choosePlan: "Choose Your Plan",
    monthlyPlan: "Monthly Plan",
    quarterlyPlan: "3-Month Plan",
    uzs: "UZS",
    month: "month",
    months: "months",
    fullAccess: "Full access to all features",
    allFeatures: "Unlimited plans and sessions",
    monthlyUpdates: "Regular notifications",
    futureUpdates: "Next month's updates",
    lockPrice: "Get updates at current price",
    selectPlan: "Select Plan",
    getBestDeal: "Get Best Deal",
    bestValue: "Best Value",
    save_m: "Save",
    priceGuarantee: "Price Lock Guarantee",
    priceGuaranteeDesc:
      "Subscribe now and lock in current pricing forever. Even if we raise prices for new features, you'll continue paying the same rate.",
    readyToUpgrade: "Ready to Upgrade?",
    contactForPremium:
      "Contact us on Telegram to activate your premium subscription",
    contactOnTelegram: "Contact on Telegram",
    buyPremiumMonthly: "I want to buy Premium - Monthly Plan",
    buyPremiumQuarterly: "I want to buy Premium - 3-Month Plan",
    premiumFeature1Title: "Smart Planning System",
    premiumFeature1Desc:
      "Create unlimited study plans for Math, Reading, and Writing sections with flexible scheduling",
    premiumFeature2Title: "Flexible Timers",
    premiumFeature2Desc:
      "Classic Pomodoro and integrated Study Room timers with customizable work-break intervals",
    premiumFeature3Title: "Smart Notifications",
    premiumFeature3Desc:
      "Get timely reminders before your study sessions start to stay on track",
    premiumFeature4Title: "Progress Tracking",
    premiumFeature4Desc:
      "Track all your study history, check-ins, and maintain accountability",
    premiumFeature5Title: "Auto-Save & Sync",
    premiumFeature5Desc:
      "Never lose progress with automatic session state saving and cloud synchronization",

    // Premium Locks
    premiumRequired: "Premium Required",
    buyPremiumToUse:
      "Subscribe to Premium to unlock all features and start your SAT prep journey",
    featureRequiresPremium: "This feature requires Premium subscription",
    upgradeToPremium: "Upgrade to Premium",
    contactSupport: "Need help? Contact",
    welcomeToPremium: "Welcome to SAT Tracker!",
    premiumActive: "Premium Active",
    expandSubscription:
      "Extend your premium subscription to continue enjoying all features",
    extendPremium: "Extend Premium",
    extendPlan: "Extend Plan",
    expires: "Expires",
  },
  uz: {
    // Dashboard
    hello: "Salom",
    friend: "Do'stim",
    readyToCrush: "SAT imtihoniga tayyormisiz?",
    createPlan: "Reja tuzish",
    startTimer: "Taymerni boshlash",
    target: "Maqsad",
    editGoal: "Maqsadni o'zgartirish",
    completeProfile: "Profilingizni to'ldiring",
    completeProfileSub:
      "Dashboardni shaxsiylashtirish uchun ismingiz va imtihon sanasini kiriting.",
    todaysPlans: "BUGUNGI REJALAR",
    fullCheckIn: "To'liq tekshirish",
    noPlansToday: "Bugun uchun rejalar yo'q",
    successQuote: "Muvaffaqiyat o'z-o'zidan kelmaydi. U rejalashtiriladi.",
    createAPlan: "Reja tuzish",
    active: "FAOL",
    done: "BAJARILDI",
    enterStudyRoom: "O'quv Xonasiga Kirish",
    buildStreak: "Streakni yarating",
    streakSub:
      "Doimiy o'qish yuqori natija kalitidir. Momentumni ushlab turish uchun har kuni tekshiruvdan o'ting.",
    goToCheckIn: "Tekshiruvga o'tish",
    studyRoom: "O'quv Xonasi",
    studyRoomSub:
      "Rejalashtirilgan maqsadlaringizni bo'lakma-bo'lak boshqaruv orqali amalga oshiring.",
    goToStudyRoom: "O'quv Xonasiga o'tish",
    quickLinks: "TEZKOR HAVOLALAR",
    studyPlanner: "O'quv Rejalashtiruvchisi",
    dailyCheckIn: "Kunlik Tekshiruv",
    studyHistory: "O'qish Tarixi",
    classicTimer: "Klassik Pomodoro Taymer",
    studyTip: "O'qish Maslahati",
    tipQuote:
      '"Oldinga siljishning siri - bu boshlashdir." — Maqsadingizga erishish uchun kunlik rejalaringizda barqaror bo\'ling.',
    loadingDashboard: "Dashboard yuklanmoqda...",
    feedback: "Fikr-mulohaza",
    haveSuggestions: "Takliflaringiz bormi?",
    planClosed: "Reja yopilgan",
    sessionUnavailableMsg:
      "Ushbu sessiya allaqachon yakunlangan yoki muddati o'tgan.",
    standBy: "Kuting",
    planScheduledFor:
      "Ushbu reja {time} ga rejalashtirilgan. Kirish o'sha vaqtda ochiladi.",

    // Profile / Settings
    settings: "Sozlamalar",
    preferencesAccount: "Afzalliklar va Hisob",
    themeEngine: "Mavzu Dvigateli",
    classic: "Klassik",
    midnight: "Yarim tun",
    ocean: "Okean",
    quickAccess: "Tezkor Kirish",
    editProfile: "Profilni Tahrirlash",
    studyArchive: "O'quv Arxivi",
    general: "Umumiy",
    shareFeedback: "Fikr Ulashish",
    aboutApp: "Ilova Haqida",
    privacyPolicy: "Maxfiylik Siyosati",
    signOut: "Chiqish",
    language: "Til",
    selectLanguage: "Tilni Tanlang",

    // Common
    error: "Xato",
    back: "Orqaga",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",

    // Plan Screen
    editPlan: "Rejani tahrirlash",
    plan: "Reja",
    refineMission: "Missiyani aniqlashtiring.",
    designPath: "Yo'lingizni loyihalashtiring.",
    selectScheduleDate: "Reja sanasini tanlang",
    focusArea: "Diqqat markazi",
    startTime: "BOSHLANISH VAQTI",
    endTime: "TUGASH VAQTI",
    executionTasks: "Bajariladigan topshiriqlar",
    divideSession: "Sessiyani aniq topshiriqlarga bo'ling...",
    saving: "Saqlanmoqda...",
    updateMission: "Missiyani yangilash",
    commitMission: "Missiyani tasdiqlash",
    instructions: "Yo'riqnoma",
    planInstructions:
      "O'rganmoqchi bo'lgan bo'limingizni tanlang va aniq vaqt oralig'ini belgilang. Diqqatni jamlash uchun vazifalaringizni aniq ko'rsating. Saqlangandan so'ng, ushbu rejalar dashboardda va tekshiruv vaqt jadvalida paydo bo'ladi.",
    math: "MATH",
    reading: "READING",
    writing: "WRITING",
    hour: "SOAT",
    min: "MIN",
    pleaseEnterTasks: "Iltimos, vazifalarni kiriting",
    minutesExceed59: "Daqiqalar 59 dan oshmasligi kerak.",
    endTimeFuture: "Missiya tugash vaqti kelajakda bo'lishi kerak.",
    minDuration: "Rejaning minimal davomiyligi 5 daqiqa bo'lishi kerak.",
    failedLoadPlan: "Rejani yuklashda xatolik yuz berdi.",
    missionUpdated: "Missiya muvaffaqiyatli yangilandi!",
    missionCommitted: "Missiya muvaffaqiyatli saqlandi!",

    // Check-in Screen
    checkIn: "Tekshiruv",
    timelineSub: "Rejalarni ko'rish yoki belgilash uchun kunni bosing",
    fullTimeline: "TO'LIQ VAQT JADVALI",
    today: "BUGUN",
    noCheckIns: "Bu kun uchun rejalar yo'q.",
    scheduleNow: "Hozir rejalashtirish →",
    howItWorks: "Qanday ishlaydi",
    checkInInfo1:
      'Sessiyalar belgilangan boshlanish vaqtidan keyin tekshirish uchun ochiq bo\'ladi. Agar topshiriqlarni bajargan bo\'lsangiz "Bajarildi", aks holda "O\'tkazib yuborildi" deb belgilang.',
    checkInInfo2:
      "Doimiy tekshiruvlar sizning natijangizni kuzatib borishga va mas'uliyatni saqlashga yordam beradi.",
    incomplete: "Bajarilmagan",
    finished: "Tugallangan",
    scheduleNewMission: "Yangi missiya rejalashtirish",
    missionDeleted: "Missiya muvaffaqiyatli o'chirildi",
    failedDelete: "Missiyani o'chirishda xatolik",
    sureDelete:
      "Ushbu missiyani o'chirishga ishonchingiz komilmi? Buni qaytarib bo'lmaydi.",
    locked: "Qulflangan",
    onlyCheckInAfterStart:
      "Faqat reja boshlanganidan keyin tekshiruvdan o'tishingiz mumkin.",
    deletePlan: "Rejani o'chirish",

    // Study Room
    studySession: "O'quv Sessiyasi",
    activeMission: "Faol Missiya",
    objectiveProgress: "MAQSAD DARAJASI",
    timerRemaining: "QOLGAN VAQT",
    finishMission: "Missiyani yakunlash",
    syncingRoom: "Xonani sinxronlash...",
    dailyRoadmap: "Kunlik rejangizni amalga oshiring",
    allMissionsComplete:
      "Bugungi barcha missiyalar bajarilgan yoki mavjud emas.",
    planNewMission: "Yangi missiya rejalashtirish",
    missionBriefing: "Missiya brifingi",
    totalTime: "UMUMIY VAQT",
    window: "VAQT ORALIG'I",
    configureStrategy: "Strategiyani sozlash",
    piecesSessions: "BO'LAKLAR (SESSIYALAR)",
    breakPerPiece: "HAR BIR BO'LAK UCHUN TANAFUS (m)",
    strategyInfo:
      "Strategiya: har biri {focus} daqiqadan iborat {sessions} ta bo'lak.",
    missionSuccess: "Missiya muvaffaqiyatli",
    missionSuccessSub:
      "Siz {section} bo'yicha intensiv o'qishni yakunladingiz. Natijani qayd etishga tayyormisiz?",
    logAsCompleted: "BAJARILDI DEB BELGILASH",
    archiving: "ARXIVLANMOQDA...",
    keepWorking: "DAVOM ETTIRISH",
    quitSession: "SESSIYADAN CHIQISH",
    overallCompletion: "UMUMIY BAJARILISH",
    missionObjective: "MISSIYA MAQSADI",
    partXofY: "{total} dan {current}-qism",
    quitSessionTitle: "Sessiyadan chiqish?",
    quitSessionMsg: "Jarayonni saqlamoqchimisiz yoki bekor qilmoqchimisiz?",
    discard: "Bekor qilish",
    saveProgress: "Saqlash",
    resetPieceMsg:
      "Ushbu bo'lakni qaytadan boshlaysizmi? Ushbu sessiya uchun jarayon yo'qoladi.",
    expired: "Muddati o'tdi",
    startsAt: "{time} da boshlanadi",
    continue: "Davom ettirish",
    missionUnavailable: "Missiya mavjud emas",
    alreadyCompleted: "Ushbu missiya allaqachon bajarilgan.",
    alreadyExpired: "Ushbu missiya muddati o'tgan.",
    failedLoadPlans: "O'quv rejalarini yuklab bo'lmadi. Aloqani tekshiring.",
    selectDate: "Sanani tanlang",
    noRecordsDate: "Ushbu sana uchun qaydlar yo'q",
    missed: "O'TKAZIB YUBORILDI",
    untracked: "KUZATILMAGAN",
    deleteRecord: "Qaydni o'chirish",
    sureDeleteRecord:
      "Ushbu o'qish qaydini o'chirishga ishonchingiz komilmi? Buni qaytarib bo'lmaydi.",
    recordDeleted: "Qayd muvaffaqiyatli o'chirildi",
    failedDeleteRecord: "Qaydni o'chirishda xatolik yuz berdi",
    failedLoadHistory: "Tarixni yuklab bo'lmadi.",
    mon: "Du",
    tue: "Se",
    wed: "Ch",
    thu: "Pa",
    fri: "Ju",
    sat: "Sha",
    sun: "Yak",

    // Edit Profile
    personalInfo: "Shaxsiy ma'lumotlar",
    name: "Ism",
    yourName: "Sizning ismingiz",
    educationLevel: "Ta'lim darajasi",
    satScores: "SAT ballari",
    targetScore: "Maqsadli ball",
    readingWriting: "O'qish va Yozish",
    totalTarget: "Umumiy maqsad",
    previousScoreOptional: "Oldingi ball (Ixtiyoriy)",
    havePreviousScore: "Oldingi SAT ballim bor",
    previousTotal: "Oldingi umumiy ball",
    saveChanges: "O'zgarishlarni saqlash",
    profileUpdated: "Profil muvaffaqiyatli yangilandi!",
    failedUpdateProfile: "Profilni yangilab bo'lmadi. Aloqani tekshiring.",
    failedLoadProfile: "Profilni yuklab bo'lmadi. Aloqani tekshiring.",
    undergraduate: "Bakalavr",
    graduate: "Magistratura",
    other: "Boshqa",
    "5th": "5-sinf",
    "6th": "6-sinf",
    "7th": "7-sinf",
    "8th": "8-sinf",
    "9th": "9-sinf",
    "10th": "10-sinf",
    "11th": "11-sinf",
    "12th": "12-sinf",
    march: "Mart",
    may: "May",
    june: "Iyun",
    august: "Avgust",
    october: "Oktyabr",
    november: "Noyabr",
    december: "Dekabr",
    aboutSATTracker: "SAT Tracker haqida",
    premiumStudyCompanion: "Premium o'quv hamrohi",
    planTrackSucceed: "Rejalashtir. Kuzat. Muvaffaqiyat qozon.",
    aboutHeroDesc:
      "Zamonaviy SAT tayyorgarligi uchun keng qamrovli vosita. Kunlik sessiyalaringizni tashkil qiling, diqqatni jamlang va natijalaringizni doimiy ravishda kuzatib boring.",
    everythingYouNeed: "Sizga kerak bo'lgan hamma narsa",
    smartToolsDesc:
      "O'qish odatlaringizni yaxshilash va samaradorlikni oshirish uchun mo'ljallangan aqlli vositalar.",
    readyOptimizeSAT: "SAT o'qishingizni optimallashtirishga tayyormisiz?",
    aboutCTADesc:
      "Maqsadingizga erishish uchun kunlik rejalaringizda barqaror bo'ling. Izchil harakat - bu maqsadlar va muvaffaqiyatlar o'rtasidagi ko'prikdir.",
    studyPlanningDesc:
      "Matematika, O'qish va Yozish bo'limlari uchun tizimli kunlik rejalar yarating. Har bir vazifa uchun aniq vaqt bloklarini belgilang.",
    focusTimerLongDesc:
      "Ish va dam olish intervallari bilan diqqatni oshiring. Sessiyalarni uzluksiz kuzatib borish uchun o'quv rejalaringiz bilan bevosita birlashtirilgan.",
    dailyCheckInsLongDesc:
      "Sessiyalaringizni yakunlangan deb belgilash orqali mas'uliyatni saqlang. Hosildorlikning kunlik seriyasini (streak) yarating.",
    progressTrackerDesc:
      "Natijalar tarixingizni ko'ring. Qaysi sessiyalarni bajarganingizni aniq ko'ring va yaxshilanishi kerak bo'lgan sohalarni aniqlang.",
    privacyHeroSub:
      "Sizning maxfiyligingiz biz uchun muhim. Ma'lumotlaringizni qanday boshqarishimiz haqida tanishing.",
    lastUpdated: "Oxirgi yangilanish: Yanvar 2026",
    questions: "Savollar bormi?",
    privacyQuestionsSub:
      "Agar ushbu maxfiylik siyosati yoki ma'lumotlaringizni qanday boshqarishimiz haqida savollaringiz bo'lsa, bizga murojaat qiling:",
    dataCollection: "Ma'lumotlarni yig'ish",
    dataCollectionContent:
      "SAT Tracker faqat xizmat ko'rsatish uchun zarur bo'lgan ma'lumotlarni yig'adi: autentifikatsiya uchun elektron pochta manzilingiz, siz yaratgan o'quv rejalari va tekshiruv qaydlari. Biz siz taqdim etgan ma'lumotlardan tashqari shaxsiy aniqlovchi ma'lumotlarni yig'maymiz.",
    dataStorage: "Ma'lumotlarni saqlash",
    dataStorageContent:
      "Ma'lumotlaringiz Supabase bulutli infratuzilmasi orqali sanoat standartidagi shifrlash bilan xavfsiz saqlanadi. Barcha ma'lumot uzatish TLS/SSL protokollari yordamida shifrlangan.",
    dataUsage: "Ma'lumotlardan foydalanish",
    dataUsageContent:
      "Biz sizning ma'lumotlaringizdan faqat SAT Tracker xizmatini taqdim etish uchun foydalanamiz. O'quv rejalaringiz va taraqqiyot ma'lumotlari uchinchi shaxslarga hech qachon berilmaydi, sotilmaydi yoki reklama maqsadlarida foydalanilmaydi.",
    yourRights: "Sizning huquqlaringiz",
    yourRightsContent:
      "Siz istalgan vaqtda ma'lumotlaringizga kirish, ularni o'zgartirish yoki o'chirish huquqiga egasiz. Ma'lumotlarni o'chirishni so'rash uchun Telegram orqali @satrackerbot bilan bog'laning.",

    // Focus / Classic Timer
    classicPomodoro: "Diqqat Taymeri",
    focusSub: "Sof konsentratsiya hududi",
    focusProgress: "DIQQAT JARAYONI",
    ready: "TAYYOR",
    focusing: "DIQQATDA",
    breaking: "TANAFFUSDA",
    adjustSessions: "SESSIYALARNI SOZLASH",
    focusDuration: "Diqqat davomiyligi (m)",
    breakDuration: "Tanaffus davomiyligi (m)",
    configTip:
      "To'xtatilgan vaqtda raqamlarni yozishingiz yoki +/- dan foydalanishingiz mumkin.",
    resetTimer: "Taymerni qayta boshlash",
    confirmReset:
      "Hozirgi sessiyani qayta boshamoqchimisiz? Jarayon yo'qoladi.",
    session: "Sessiya",
    break: "Tanaffus",
    start: "Boshlash",
    pause: "To'xtatish",
    reset: "Qayta boshlash",
    success: "Muvaffaqiyat",
    notAuthenticated: "Autentifikatsiyadan o'tilmagan",
    noInternet: "Internet aloqasi yo'q.",
    failedSavePlan: "Rejani saqlab bo'lmadi.",
    failedSaveStatus: "Holatni saqlab bo'lmadi.",
    examDate: "Imtihon sanasi",
    allRightsReserved: "Barcha huquqlar himoyalangan",
    welcomeBack: "Xush kelibsiz",
    signInToContinue:
      "SAT tayyorgarligi bo'yicha sayohatingizni davom ettirish uchun tizimga kiring",
    emailAddress: "Elektron pochta manzili",
    signIn: "Tizimga kirish",
    signingIn: "Kirilmoqda...",
    forgotPassword: "Parolni unutdingizmi?",
    or: "YOKI",
    createNewAccount: "Yangi hisob yaratish",
    backToSignIn: "Tizimga kirishga qaytish",
    checkYourEmail: "Elektron pochtangizni tekshiring",
    weSentResetLink:
      "Biz {email} manziliga parolni tiklash havolasini yubordik",
    resendEmail: "E-pochtani qayta yuborish",
    resending: "Qayta yuborilmoqda...",
    needHelp: "Yordam kerakmi?",
    enterEmailReset:
      "Elektron pochtangizni kiriting va biz sizga tiklash havolasini yuboramiz",
    sendResetLink: "Tiklash havolasini yuborish",
    sending: "Yuborilmoqda...",
    createAccount: "Hisob yaratish",
    tellUsAboutYou: "O'zingiz haqingizda gapirib bering",
    satGoals: "Sizning SAT maqsadlaringiz",
    setUpCredentials: "Hisob ma'lumotlarini sozlang",
    personalizeExperience: "Biz sizning tajribangizni individuallashtiramiz",
    trackProgress: "Natijalaringizni kuzatishga yordam bering",
    preferredName: "Ismingiz",
    namePlaceholder: "Sizga qanday murojaat qilishimizni xohlaysiz?",
    confirmPassword: "Parolni tasdiqlang",
    hints: "Kamida 6 ta belgi, harflar va raqamlar bilan",
    dontHaveAccount: "Hisobingiz yo'qmi?",
    alreadyHaveAccount: "Hisobingiz bormi?",
    checking: "Tekshirilmoqda...",
    completeSignup: "Ro'yxatdan o'tishni yakunlash",
    creatingAccount: "Hisob yaratilmoqda...",
    skip: "O'tkazib yuborish",
    notifications: "Bildirishnomalar",
    newUpdates: "YANGI YANGILANISHLAR",
    pastNotifications: "AVVALGI BILDIRISHNOMALAR",
    noNotificationsYet: "Hozircha bildirishnomalar yo'q",
    showMore: "Batafsil ko'rish",
    showLess: "Qisqartirish",
    goToPlanner: "Rejalashtiruvchiga o'tish",
    checkInNow: "Hozir tekshirish",
    markAllRead: "Hammasini o'qilgan deb belgilash",
    planUnavailable: "Reja mavjud emas",
    invalidCredentials:
      "Kirish ma'lumotlari noto'g'ri. Elektron pochta va parolni tekshiring.",
    emailNotConfirmed:
      "Tizimga kirishdan oldin elektron pochta manzilingizni tasdiqlang.",
    userNotFound: "Ushbu elektron pochta manzili mavjud emas.",
    loginFailed:
      "Tizimga kirishda xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
    failedSendReset: "Parolni tiklash elektron pochtasini yuborib bo'lmadi.",
    enterEmail: "Iltimos, elektron pochta manzilingizni kiriting.",
    enterPassword: "Iltimos, parolingizni kiriting.",
    createPassword: "Iltimos, yangi parol yarating.",
    passwordRequirements:
      "Parol kamida 6 ta belgidan iborat bo'lishi hamda harf va raqamlarni o'z ichiga olishi kerak.",
    passwordsDoNotMatch:
      "Tasdiqlash paroli mos kelmadi. Iltimos, qayta urinib ko'ring.",
    completeRequiredFields:
      "Tajribangizni individuallashtirish uchun barcha majburiy maydonlarni to'ldiring.",
    accountCreatedSuccess: "Hisob muvaffaqiyatli yaratildi!",
    checkEmailVerify:
      "Hisobingizni tasdiqlash uchun elektron pochtangizni tekshiring.",
    unexpectedError: "Kutilmagan xatolik yuz berdi.",
    userAlreadyExists:
      "Foydalanuvchi allaqachon mavjud. Boshqa elektron pochta kiriting.",
    invalidEmail: "To'g'ri elektron pochta manzilini kiriting.",
    january: "Yanvar",
    february: "Fevral",
    april: "Aprel",
    july: "Iyul",
    september: "Sentyabr",
    daysShort: "K",
    hoursShort: "S",
    minutesShort: "D",
    secondsShort: "S",
    at: "soat",
    failedFetchData: "Ma'lumotlarni yuklab bo'lmadi. Server xatosi.",
    noInternetCheck: "Internet aloqasi yo'q. Tarmoqni tekshirib qayta urining.",

    // Premium Page
    getPremium: "Premium olish",
    unlockAllFeatures:
      "Barcha funksiyalarni ochib, SAT tayyorgarligingizni maksimal darajaga ko'taring",
    whatYouGet: "Nima olasiz",
    choosePlan: "Rejani tanlang",
    monthlyPlan: "Oylik Reja",
    quarterlyPlan: "3-Oylik Reja",
    uzs: "so'm",
    month: "oy",
    months: "oy",
    fullAccess: "Barcha funksiyalarga to'liq kirish",
    allFeatures: "Cheksiz rejalar va sessiyalar",
    monthlyUpdates: "Muntazam bildirishnomalar",
    futureUpdates: "Keyingi oydagi yangilanishlar",
    lockPrice: "Joriy narxda yangilanishlarga ega chiqish",
    selectPlan: "Rejani tanlash",
    getBestDeal: "Eng yaxshi taklifni oling",
    bestValue: "Eng foydali",
    save_m: "Tejang",
    priceGuarantee: "Narx kafolati",
    priceGuaranteeDesc:
      "Hozir obuna bo'ling va joriy narxda yangilanishlarga ega chiqing. Agar yangi funksiyalar uchun narxlarni oshirsak ham, siz bir xil to'lovni davom ettirasiz.",
    readyToUpgrade: "Yangilashga tayyormisiz?",
    contactForPremium:
      "Premium obunangizni faollashtirish uchun Telegram orqali bog'laning",
    contactOnTelegram: "Telegram orqali bog'lanish",
    buyPremiumMonthly: "Premium obuna - Oylik Reja",
    buyPremiumQuarterly: "Premium obuna - 3-Oylik Reja",
    premiumFeature1Title: "Aqlli rejalashtirish tizimi",
    premiumFeature1Desc:
      "Matematik, O'qish va Yozish bo'limlari uchun moslashuvchan jadval bilan cheksiz o'quv rejalarini yarating",
    premiumFeature2Title: "Moslashuvchan taymerlar",
    premiumFeature2Desc:
      "Klassik Pomodoro va integratsiyalashgan O'quv Xonasi taymerlari bilan sozlanishi mumkin bo'lgan ish-tanaffus intervalilari",
    premiumFeature3Title: "Aqlli bildirishnomalar",
    premiumFeature3Desc:
      "O'quv sessiyangiz boshlanishidan oldin o'z vaqtida eslatmalar oling va rejada qoling",
    premiumFeature4Title: "Taraqqiyotni kuzatish",
    premiumFeature4Desc:
      "Barcha o'quv tarixingiz, tekshiruvlaringiz va mas'uliyatni kuzatib boring",
    premiumFeature5Title: "Avtomatik saqlash va sinxronlash",
    premiumFeature5Desc:
      "Avtomatik sessiya holatini saqlash va bulut sinxronlashuvi bilan hech qachon jarayoningizni yo'qotmang",

    // Premium Locks
    premiumRequired: "Premium talab qilinadi",
    buyPremiumToUse:
      "Barcha funksiyalarni ochish va SAT tayyorgarligini boshlash uchun Premium obuna bo'ling",
    featureRequiresPremium: "Ushbu funksiya Premium obuna talab qiladi",
    upgradeToPremium: "Premium ga yangilash",
    contactSupport: "Yordam kerakmi? Bog'laning",
    welcomeToPremium: "SAT Tracker ga xush kelibsiz!",
    premiumActive: "Premium faol",
    expandSubscription:
      "Barcha funksiyalardan foydalanishni davom ettirish uchun premium obunangizni uzaytiring",
    extendPremium: "Premium ni uzaytirish",
    extendPlan: "Rejani uzaytirish",
    expires: "Tugaydi",
  },
  ru: {
    // Dashboard
    hello: "Привет",
    friend: "Друг",
    readyToCrush: "Готов сдать SAT на отлично?",
    createPlan: "Создать план",
    startTimer: "Запустить таймер",
    target: "Цель",
    editGoal: "Изменить цель",
    completeProfile: "Заполните профиль",
    completeProfileSub:
      "Укажите имя и дату экзамена для персонализации дашборда.",
    todaysPlans: "ПЛАНЫ НА СЕГОДНЯ",
    fullCheckIn: "Полная проверка",
    noPlansToday: "На сегодня планов нет",
    successQuote: "Успех не приходит сам собой. Его планируют.",
    createAPlan: "Создать план",
    active: "АКТИВНО",
    done: "ГОТОВО",
    enterStudyRoom: "Войти в учебную комнату",
    buildStreak: "Собери свою серию",
    streakSub:
      "Постоянство - ключ к высокому баллу. Отмечайся ежедневно, чтобы не терять темп.",
    goToCheckIn: "Перейти к проверке",
    studyRoom: "Учебная комната",
    studyRoomSub:
      "Выполняйте запланированные задачи с помощью пошагового управления.",
    goToStudyRoom: "В учебную комнату",
    quickLinks: "БЫСТРЫЕ ССЫЛКИ",
    studyPlanner: "Планировщик",
    dailyCheckIn: "Ежедневная проверка",
    studyHistory: "История обучения",
    classicTimer: "Классический таймер",
    studyTip: "Совет по учебе",
    tipQuote:
      '"Секрет продвижения вперед — это начать." — Будьте последовательны в своих ежедневных планах, чтобы достичь цели.',
    loadingDashboard: "Загрузка дашборда...",
    feedback: "Обратная связь",
    haveSuggestions: "Есть предложения?",
    planClosed: "План закрыт",
    sessionUnavailableMsg:
      "Эта сессия уже завершена или срок ее действия истек.",
    standBy: "Подождите",
    planScheduledFor:
      "Этот план запланирован на {time}. Доступ откроется в это время.",

    // Profile / Settings
    settings: "Настройки",
    preferencesAccount: "Настройки и Аккаунт",
    themeEngine: "Тема",
    classic: "Классика",
    midnight: "Полночь",
    ocean: "Океан",
    quickAccess: "Быстрый доступ",
    editProfile: "Ред. профиль",
    studyArchive: "Архив занятий",
    general: "Общее",
    shareFeedback: "Поделиться мнением",
    aboutApp: "О приложении",
    privacyPolicy: "Политика конфиденциальности",
    signOut: "Выйти",
    language: "Язык",
    selectLanguage: "Выберите язык",

    // Common
    error: "Ошибка",
    back: "Назад",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",

    // Plan Screen
    editPlan: "Изменить план",
    plan: "План",
    refineMission: "Уточните свою миссию.",
    designPath: "Спроектируйте свой путь к успеху.",
    selectScheduleDate: "Выберите дату",
    focusArea: "Область внимания",
    startTime: "ВРЕМЯ НАЧАЛА",
    endTime: "ВРЕМЯ ОКОНЧАНИЯ",
    executionTasks: "Задачи на выполнение",
    divideSession: "Разделите занятие на конкретные задачи...",
    saving: "Сохранение...",
    updateMission: "Обновить миссию",
    commitMission: "Подтвердить миссию",
    instructions: "Инструкции",
    planInstructions:
      "Выберите раздел и установите четкие временные рамки. Будьте конкретны в задачах. Планы появятся на дашборде и в графике проверок.",
    math: "МАТЕМАТИКА",
    reading: "ЧТЕНИЕ",
    writing: "ПИСЬМО",
    hour: "ЧАС",
    min: "МИН",
    pleaseEnterTasks: "Пожалуйста, введите задачи",
    minutesExceed59: "Минуты не могут превышать 59.",
    endTimeFuture: "Время окончания должно быть в будущем.",
    minDuration: "Минимальная длительность плана - 5 минут.",
    failedLoadPlan: "Не удалось загрузить план для редактирования.",
    missionUpdated: "Миссия успешно обновлена!",
    missionCommitted: "Миссия успешно создана!",

    // Check-in Screen
    checkIn: "Проверка",
    timelineSub: "Нажмите на день, чтобы просмотреть или отметить планы",
    fullTimeline: "ПОЛНЫЙ ГРАФИК",
    today: "СЕГОДНЯ",
    noCheckIns: "На этот день планов нет.",
    scheduleNow: "Запланировать сейчас →",
    howItWorks: "Как это работает",
    checkInInfo1:
      "Сессии становятся доступными для проверки после их запланированного времени начала. Отмечайте планы как «Выполнено», если вы закончили задачи, или «Пропущено», если не смогли.",
    checkInInfo2:
      "Регулярные проверки помогают отслеживать прогресс и поддерживать учебную дисциплину.",
    incomplete: "Не завершено",
    finished: "Завершено",
    scheduleNewMission: "Запланировать новую миссию",
    missionDeleted: "Миссия успешно удалена",
    failedDelete: "Не удалось удалить миссию",
    sureDelete:
      "Вы уверены, что хотите удалить эту миссию? Это действие нельзя отменить.",
    locked: "Заблокировано",
    onlyCheckInAfterStart: "Вы можете отметиться только после начала плана.",
    deletePlan: "Удалить план",

    // Study Room
    studySession: "Учебная сессия",
    activeMission: "Активная миссия",
    objectiveProgress: "ПРОГРЕСС",
    timerRemaining: "ОСТАЛОСЬ",
    finishMission: "Завершить миссию",
    syncingRoom: "Синхронизация комнаты...",
    dailyRoadmap: "Выполняйте свой ежедневный план",
    allMissionsComplete: "Все задачи на сегодня выполнены или отсутствуют.",
    planNewMission: "Запланировать новую задачу",
    missionBriefing: "Брифинг миссии",
    totalTime: "ОБЩЕЕ ВРЕМЯ",
    window: "ОКНО",
    configureStrategy: "Настройка стратегии",
    piecesSessions: "ЧАСТИ (СЕССИИ)",
    breakPerPiece: "ПЕРЕРЫВ НА ЧАСТЬ (м)",
    strategyInfo: "Стратегия: {sessions} частей по {focus}м каждая.",
    missionSuccess: "Миссия выполнена",
    missionSuccessSub:
      "Вы завершили интенсивное изучение {section}. Готовы зафиксировать прогресс?",
    logAsCompleted: "ОТМЕТИТЬ КАК ВЫПОЛНЕННОЕ",
    archiving: "АРХИВАЦИЯ...",
    keepWorking: "ПРОДОЛЖИТЬ РАБОТУ",
    quitSession: "ВЫЙТИ ИЗ СЕССИИ",
    overallCompletion: "ОБЩИЙ ПРОГРЕСС",
    missionObjective: "ЦЕЛЬ МИССИИ",
    partXofY: "Часть {current} из {total}",
    quitSessionTitle: "Выйти из сессии?",
    quitSessionMsg: "Вы хотите сохранить прогресс или отменить его?",
    discard: "Отменить",
    saveProgress: "Сохранить",
    resetPieceMsg:
      "Перезапустить эту часть? Текущий прогресс этой сессии будет потерян.",
    expired: "Истекло",
    startsAt: "Начало в {time}",
    continue: "Продолжить",
    missionUnavailable: "Миссия недоступна",
    alreadyCompleted: "Эта миссия уже выполнена.",
    alreadyExpired: "Срок действия этой миссии истек.",
    failedLoadPlans:
      "Не удалось загрузить учебные планы. Проверьте соединение.",
    selectDate: "Выберите дату",
    noRecordsDate: "Нет записей на эту дату",
    missed: "ПРОПУЩЕНО",
    untracked: "НЕ ОТСЛЕЖИВАЕТСЯ",
    deleteRecord: "Удалить запись",
    sureDeleteRecord:
      "Вы уверены, что хотите удалить эту учебную запись? Это действие нельзя отменить.",
    recordDeleted: "Запись успешно удалена",
    failedDeleteRecord: "Не удалось удалить запись",
    failedLoadHistory: "Не удалось загрузить историю.",
    mon: "Пн",
    tue: "Вт",
    wed: "Ср",
    thu: "Чт",
    fri: "Пт",
    sat: "Сб",
    sun: "Вс",

    // Edit Profile
    personalInfo: "Личная информация",
    name: "Имя",
    yourName: "Ваше имя",
    educationLevel: "Уровень образования",
    satScores: "Баллы SAT",
    targetScore: "Целевой балл",
    readingWriting: "Чтение и Письмо",
    totalTarget: "Общая цель",
    previousScoreOptional: "Предыдущий балл (Опционально)",
    havePreviousScore: "У меня есть предыдущий балл SAT",
    previousTotal: "Предыдущий общий балл",
    saveChanges: "Сохранить изменения",
    profileUpdated: "Профиль успешно обновлен!",
    failedUpdateProfile: "Не удалось обновить профиль. Проверьте соединение.",
    failedLoadProfile: "Не удалось загрузить профиль. Проверьте соединение.",
    undergraduate: "Бакалавриат",
    graduate: "Магистратура",
    other: "Другое",
    "5th": "5 класс",
    "6th": "6 класс",
    "7th": "7 класс",
    "8th": "8 класс",
    "9th": "9 класс",
    "10th": "10 класс",
    "11th": "11 класс",
    "12th": "12 класс",
    march: "Март",
    may: "Май",
    june: "Июнь",
    august: "Август",
    october: "Октябрь",
    november: "Ноябрь",
    december: "Декабрь",
    aboutSATTracker: "О SAT Tracker",
    premiumStudyCompanion: "Премиальный помощник",
    planTrackSucceed: "Планируй. Отслеживай. Успевай.",
    aboutHeroDesc:
      "Комплексный инструмент для современной подготовки к SAT. Организуйте свои ежедневные занятия, сохраняйте концентрацию и последовательно отслеживайте свой прогресс.",
    everythingYouNeed: "Все, что вам нужно",
    smartToolsDesc:
      "Умные инструменты, разработанные для улучшения ваших учебных навыков и повышения эффективности.",
    readyOptimizeSAT: "Готовы оптимизировать подготовку к SAT?",
    aboutCTADesc:
      "Будьте последовательны в своих ежедневных планах, чтобы достичь цели. Постоянные усилия - это мост между целями и достижениями.",
    studyPlanningDesc:
      "Создавайте структурированные ежедневные планы для разделов математики, чтения и письма. Устанавливайте четкие временные блоки для каждой задачи.",
    focusTimerLongDesc:
      "Повысьте концентрацию с помощью интервалов работы и отдыха. Интегрировано с вашими учебными планами для плавного отслеживания занятий.",
    dailyCheckInsLongDesc:
      "Поддерживайте дисциплину, отмечая занятия как выполненные. Соберите ежедневную серию продуктивности.",
    progressTrackerDesc:
      "Просматривайте историю своих успехов. Видьте, какие именно занятия вы выполнили, и определяйте области для улучшения.",
    privacyHeroSub:
      "Ваша конфиденциальность важна для нас. Вот как мы обрабатываем ваши данные.",
    lastUpdated: "Последнее обновление: Январь 2026",
    questions: "Вопросы?",
    privacyQuestionsSub:
      "Если у вас есть какие-либо вопросы об этой политике конфиденциальности или о том, как мы обрабатываем ваши данные, пожалуйста, свяжитесь с нами:",
    dataCollection: "Сбор данных",
    dataCollectionContent:
      "SAT Tracker собирает только необходимую информацию для предоставления нашего сервиса: ваш адрес электронной почты для аутентификации, созданные вами учебные планы и записи о посещаемости. Мы не собираем личную идентифицирующую информацию, кроме той, которую вы явно предоставляете.",
    dataStorage: "Хранение данных",
    dataStorageContent:
      "Ваши данные надежно хранятся с использованием облачной инфраструктуры Supabase с использованием стандартного отраслевого шифрования. Все передачи данных зашифрованы с использованием протоколов TLS/SSL.",
    dataUsage: "Использование данных",
    dataUsageContent:
      "Мы используем ваши данные исключительно для предоставления сервиса SAT Tracker. Ваши учебные планы и данные о прогрессе никогда не передаются третьим лицам, не продаются и не используются в рекламных целях.",
    yourRights: "Ваши права",
    yourRightsContent:
      "Вы имеете право на доступ, изменение или удаление своих данных в любое время. Чтобы запросить удаление данных, пожалуйста, свяжитесь с нами через Telegram по адресу @satrackerbot.",

    // Focus / Classic Timer
    classicPomodoro: "Таймер фокуса",
    focusSub: "Зона чистой концентрации",
    focusProgress: "ПРОГРЕСС ФОКУСА",
    ready: "ГОТОВ",
    focusing: "В ФОКУСЕ",
    breaking: "ПЕРЕРЫВ",
    adjustSessions: "НАСТРОЙКА СЕССИЙ",
    focusDuration: "Длительность фокуса (м)",
    breakDuration: "Длительность перерыва (м)",
    configTip: "Вы можете вводить числа или использовать +/- во время паузы.",
    resetTimer: "Сбросить таймер",
    confirmReset:
      "Вы уверены, что хотите сбросить текущую сессию? Прогресс будет потерян.",
    session: "Сессия",
    break: "Перерыв",
    start: "Старт",
    pause: "Пауза",
    reset: "Сброс",
    success: "Успех",
    notAuthenticated: "Не аутентифицирован",
    noInternet: "Нет подключения к интернету.",
    failedSavePlan: "Не удалось сохранить план.",
    failedSaveStatus: "Не удалось сохранить статус.",
    examDate: "Дата экзамена",
    allRightsReserved: "Все права защищены",
    welcomeBack: "С возвращением",
    signInToContinue: "Войдите, чтобы продолжить подготовку к SAT",
    emailAddress: "Адрес электронной почты",
    signIn: "Войти",
    signingIn: "Вход...",
    forgotPassword: "Забыли пароль?",
    or: "ИЛИ",
    createNewAccount: "Создать новый аккаунт",
    backToSignIn: "Назад ко входу",
    checkYourEmail: "Проверьте почту",
    weSentResetLink: "Мы отправили ссылку для сброса пароля на {email}",
    resendEmail: "Отправить письмо еще раз",
    resending: "Повторная отправка...",
    needHelp: "Нужна помощь?",
    enterEmailReset:
      "Введите ваш email, и мы отправим ссылку для сброса пароля",
    sendResetLink: "Отправить ссылку",
    sending: "Отправка...",
    createAccount: "Создать аккаунт",
    tellUsAboutYou: "Расскажите о себе",
    satGoals: "Ваши цели SAT",
    setUpCredentials: "Настройте свои учетные данные",
    personalizeExperience: "Мы настроим приложение под вас",
    trackProgress: "Помогите нам отслеживать ваш прогресс",
    preferredName: "Предпочитаемое имя",
    namePlaceholder: "Как нам к вам обращаться?",
    confirmPassword: "Подтвердите пароль",
    hints: "Минимум 6 символов, буквы и цифры",
    alreadyHaveAccount: "Уже есть аккаунт? Войти",
    checking: "Проверка...",
    completeSignup: "Завершить регистрацию",
    creatingAccount: "Создание аккаунта...",
    skip: "Пропустить",
    notifications: "Уведомления",
    newUpdates: "НОВЫЕ ОБНОВЛЕНИЯ",
    pastNotifications: "ПРОШЛЫЕ УВЕДОМЛЕНИЯ",
    noNotificationsYet: "Уведомлений пока нет",
    showMore: "Показать больше",
    showLess: "Показать меньше",
    goToPlanner: "Перейти к планировщику",
    checkInNow: "Отметиться сейчас",
    markAllRead: "Отметить все как прочитанные",
    planUnavailable: "План недоступен",
    invalidCredentials:
      "Неверные учетные данные. Пожалуйста, проверьте свой email и пароль.",
    emailNotConfirmed:
      "Пожалуйста, подтвердите свой адрес электронной почты перед входом.",
    userNotFound: "Этот адрес электронной почты не зарегистрирован.",
    loginFailed: "Ошибка входа. Пожалуйста, попробуйте снова.",
    failedSendReset: "Не удалось отправить письмо для сброса пароля.",
    enterEmail: "Пожалуйста, введите свой адрес электронной почты.",
    enterPassword: "Пожалуйста, введите свой пароль.",
    createPassword: "Пожалуйста, создайте новый пароль.",
    passwordRequirements:
      "Пароль должен содержать не менее 6 символов, включая буквы и цифры.",
    passwordsDoNotMatch: "Пароли не совпадают. Пожалуйста, попробуйте снова.",
    completeRequiredFields:
      "Пожалуйста, заполните все обязательные поля для персонализации.",
    accountCreatedSuccess: "Аккаунт успешно создан!",
    checkEmailVerify:
      "Пожалуйста, проверьте свою электронную почту, чтобы подтвердить аккаунт.",
    unexpectedError: "Произошла непредвиденная ошибка.",
    userAlreadyExists: "Пользователь уже существует. Введите другой email.",
    invalidEmail: "Введите корректный адрес электронной почты.",
    january: "Январь",
    february: "Февраль",
    april: "Апрель",
    july: "Июль",
    september: "Сентябрь",
    daysShort: "Д",
    hoursShort: "Ч",
    minutesShort: "М",
    secondsShort: "С",
    at: "в",
    failedFetchData: "Не удалось загрузить данные. Ошибка сервера.",
    noInternetCheck:
      "Нет подключения к интернету. Проверьте сеть и попробуйте снова.",

    // Premium Page
    getPremium: "Получить Premium",
    unlockAllFeatures: "Откройте все функции и максимизируйте подготовку к SAT",
    whatYouGet: "Что вы получите",
    choosePlan: "Выберите тариф",
    monthlyPlan: "Месячный тариф",
    quarterlyPlan: "Тариф на 3 месяца",
    uzs: "сум",
    month: "месяц",
    months: "месяца",
    fullAccess: "Полный доступ ко всем функциям",
    allFeatures: "Неограниченные планы и сессии",
    monthlyUpdates: "Регулярные уведомления",
    futureUpdates: "Обновления следующего месяца",
    lockPrice: "Получать обновления по текущей цене",
    selectPlan: "Выбрать план",
    getBestDeal: "Лучшее предложение",
    bestValue: "Лучшая цена",
    save_m: "Сэкономьте",
    priceGuarantee: "Гарантия фиксированной цены",
    priceGuaranteeDesc:
      "Подпишитесь сейчас и получайте обновления по текущей цене. Даже если мы повысим цены на новые функции, вы продолжите платить по той же ставке.",
    readyToUpgrade: "Готовы к обновлению?",
    contactForPremium:
      "Свяжитесь с нами в Telegram, чтобы активировать premium подписку",
    contactOnTelegram: "Связаться в Telegram",
    buyPremiumMonthly: "Хочу купить Premium - Месячный тариф",
    buyPremiumQuarterly: "Хочу купить Premium - Тариф на 3 месяца",
    premiumFeature1Title: "Умная система планирования",
    premiumFeature1Desc:
      "Создавайте неограниченное количество учебных планов для разделов Math, Reading и Writing с гибким расписанием",
    premiumFeature2Title: "Гибкие таймеры",
    premiumFeature2Desc:
      "Классический Pomodoro и интегрированные таймеры Study Room с настраиваемыми интервалами работы и отдыха",
    premiumFeature3Title: "Умные уведомления",
    premiumFeature3Desc:
      "Получайте своевременные напоминания перед началом учебных сессий",
    premiumFeature4Title: "Отслеживание прогресса",
    premiumFeature4Desc:
      "Отслеживайте всю историю занятий, отметки и поддерживайте ответственность",
    premiumFeature5Title: "Автосохранение и синхронизация",
    premiumFeature5Desc:
      "Никогда не теряйте прогресс с автоматическим сохранением состояния сессии и облачной синхронизацией",

    // Premium Locks
    premiumRequired: "Требуется Premium",
    buyPremiumToUse:
      "Подпишитесь на Premium, чтобы разблокировать все функции и начать подготовку к SAT",
    featureRequiresPremium: "Эта функция требует Premium подписку",
    upgradeToPremium: "Обновить до Premium",
    contactSupport: "Нужна помощь? Свяжитесь",
    welcomeToPremium: "Добро пожаловать в SAT Tracker!",
    premiumActive: "Premium активен",
    expandSubscription:
      "Продлите подписку Premium, чтобы продолжить пользоваться всеми функциями",
    extendPremium: "Продлить Premium",
    extendPlan: "Продлить план",
    expires: "Истекает",
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "uz",
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [language, setLanguageState] = useState<Language>("en");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadLanguage = async () => {
      const saved = await AsyncStorage.getItem("user-language");
      if (saved) setLanguageState(saved as Language);
      setLoading(false);
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    await AsyncStorage.setItem("user-language", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
